title: ByVasco – Designer and Developer for the web
email: madebyvasco@gmail.com
description:
baseurl: ""
url: "https://byvasco.com"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed


collections_dir: collections

collections:
  articles:
    output: true
    permalink: /:title
  
  pages:
    output: true
    permalink: /:title
  
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "articles"
    values:
      page_title: "article"
      layout: "article"